[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
base = "dark"
primaryColor = "#eee"
backgroundColor = "#111"
secondaryBackgroundColor = "#333"
textColor = "#fff"
font = "sans serif"

[runner]
fastReruns = true
